### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by justifyer** [ollieread/multiauth#86]
This seems like a great package and I regret that haven't found it in my previous projects. With the release of Laravel 5, I started my new projects with it too. It would be great too if you would release the version that supports 5. I know you planned it, but is there any new news? Like how's the progress and such and when you expect to release it? If you've not done anything yet I might find some time at home to do it.

**Comment by visualcom** [comment]
+1

**Comment by dayed** [comment]
+1

**Comment by wulongqiu** [comment]
+1

**Comment by hiperion85** [comment]
+1

**Comment by dvigueras** [comment]
:+1:

**Comment by llaski** [comment]
+1

**Comment by jithujose** [comment]
:+1: :+1:

**Comment by Dubz** [comment]
+1

**Comment by Dubz** [comment]
It appears @ollieread already responded to this issue and closed it.
https://github.com/ollieread/multiauth/issues/82

I guess its up to another user to do this. I'd volunteer, but I just started using laravel so I wouldn't even know where to begin.

**Comment by Dubz** [comment]
Check the bottom of this form post on laracsts, maybe it will help some of you. I haven't tried it yet but I'm about to. Perhaps @ollieread can update this git using the information?

https://laracasts.com/discuss/channels/general-discussion/multiple-authentication-in-laravel-5-ldap-and-default-auth

**Comment by ollieread** [comment]
It's more that I haven't had much time to do this yet as I've been working a lot. I will do when I get chance, but others are welcome to make PRs.

**Comment by Dubz** [comment]
Well that stinks, I guess I'll have to work around that part of the system I'm creating as best as I can. I think this issue should remain open however so other users trying to figure out why this won't work on laravel 5 can see it. I wouldn't have thought to look in the closed section of the issues area when I first realized it and would have made a duplicate post. I see the closed being a solved/declined rather than a pending/on hold. That's just my opinion.

**Comment by sboo** [comment]
Check my fork https://github.com/sboo/multiauth and post on laracasts. maybe that helps

https://laracasts.com/discuss/channels/general-discussion/multiple-authentication-in-laravel-5-ldap-and-default-auth/replies/44260

**Comment by visualcom** [comment]
Hi!

I'm using Laravel 5 native auth to handle multiple auth contexts (database
tables)... It's not difficult, please check this Gist:

https://gist.github.com/danielcoimbra/64b779b4d9e522bc3373

Daniel

2015-03-18 22:40 GMT-03:00 Dubz <notifications@github.com>:

**Comment by sahibalejandro** [comment]
@visualcom Changing the value of auth.model is a clever solution, but the session data still the same for both auth contexts, causing when you call Auth::logout() both "sessions" are closed.

This is because Guard::getName() use the same name for the session data no matter what model we are using... :/

It seems we need a more complex solution like @sboo repo.
